language: java
script: 
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn verify deploy --settings maven_deploy_settings.xml || mvn test verify --settings maven_deploy_settings.xml'
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7
notifications:
  email:
    recipients:
    - yammer-sonatype@microsoft.com
env:
  global:
  - secure: v7aLGiynYsXsofGA6niM+K5C3SpbV+0rsCq2iiMpCbnNlNe+IbHTlNnnan4SnK0Igon7koJ/h/7FQ7HzsKqFbPkfM00QyFeK5jLiO33JV/aSpbm4BtWH2CQ4O3BVRHekhQJt3Ov2Laezy/muS8kvFsLRjmkuUjPcH8alN0eDflE=
  - secure: QswYjegPlf/R8ZnHCEuh2amm7XP17SpIBEdWjgWd3peLIBwP21Ge4jUed1CYdPQbVw7xvJPcRfk/jlMB6S4UpT0Eay63vcDcDoPrBXokvr1wpWI+LFP+U8WxKzOCS8V2nh+fzqLGjqEK9wkgviwFOkdm7dU4osZ9aS/uH1eIpSg=
